### ISSUE TITLE
Bug with large files

### ISSUE THREAD

**Issue by N1q** [irajsb/UE4_Assimp#19]
**Large files not loading correctly**
For some reason, some of the objects lose their position and move to the zero position.
Also, displaying an imported model uses a lot of resources, which does not happen if the model is simply imported into the unreal engine outside of runtime mode.

**To Reproduce**
Simply try to open .fbx or .gltf (didn't tried any other formats) file with lots of small elements.
Used latest release: https://github.com/irajsb/UE4_Assimp/releases/tag/5.4.2CustomFlagsSupport

**Screenshots**
![изображение](https://user-images.githubusercontent.com/33962843/188110639-90da08db-23dc-4f84-b1ce-5128cc07fa3f.png)

**Comment by irajsb** [comment]
Can you provide the model for debugging ?

**Comment by N1q** [comment]
Oh, sorry. Forgot to attach
[UE4_assimp_big_test_file.zip](https://github.com/irajsb/UE4_Assimp/files/9485857/UE4_assimp_big_test_file.zip)

**Comment by irajsb** [comment]
For performance issues : procedural mesh components are inefficient and must not be used unless its necessary . The reason that when importing using engine is more efficient is because engine takes about 2 mins to create static mesh data for meshes . This process is not related to mesh importer but engine and mesh components . I recommend trying [Runtime Mesh Component ](https://github.com/TriAxis-Games/RuntimeMeshComponent)  which is more efficient and also has support for runtime static mesh creation. 
I'm working on transforms issue at the moment will have to find a solution that produces similar result for all formats

**Comment by irajsb** [comment]
Update: After a few hours I managed to create an static mesh based solution . an update will be released soon

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/StaticMeshSupport
Transforms work and static meshes are efficient .
I've noticed a bug where only one type of mesh goes missing but that will be a different issue .
You can bypass this issue for now by adding Pre transform vertices flag in import function .

**Comment by N1q** [comment]
Thanks for the quick response!
The model is perfectly imported using **pre transform** flag.
But I need each object to be imported separately, so I'm patiently waiting for this fix as well.

**Comment by N1q** [comment]
Should I open another issue for it?

**Comment by irajsb** [comment]
I'll try again once I find some free type to debug this issue

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/MeshInstancing
