### ISSUE TITLE
External texture import

### ISSUE THREAD

**Issue by zhang8043** [irajsb/UE4_Assimp#23]
After importing, the material of the model itself is not loaded. Does it lose the original meaning of Assist.

**Comment by zhang8043** [comment]
If a model contains multiple materials, do you want to create all materials in the engine in advance?

**Comment by irajsb** [comment]
each material section is a separate mesh in assimp. are you using the sample project in releases tab?

**Comment by zhang8043** [comment]
Yes, 5.4.2 EmbeddedTextureImport also has no material

**Comment by zhang8043** [comment]
![image](https://user-images.githubusercontent.com/31415437/205081470-c5265f65-3fc1-46a6-8cc3-4ac1f9408c3d.png)

**Comment by zhang8043** [comment]
All imported models are of this color

**Comment by irajsb** [comment]
Can you share one of the models so I can test for myself?

**Comment by zhang8043** [comment]
https://github.com/assimp/assimp-mdb/tree/master/model-db/Obj/Spider

**Comment by zhang8043** [comment]
Hello, you can use this OBJ model to test

**Comment by zhang8043** [comment]
![image](https://user-images.githubusercontent.com/31415437/205193873-e1266735-d949-47e8-9e67-75faaf75af4d.png)

After importing UE

![image](https://user-images.githubusercontent.com/31415437/205193833-fa284084-6bea-4963-b42a-fec23a1064e4.png)

**Comment by irajsb** [comment]
That spider doesn't have embedded textures it has external textures . You have to pack textures inside the model in order to auto import them . if textures are not embedded assimp only gives you a path to textures and you've to import them yourself .   
The reasons that I don't add support for auto importing external textures are :  
1- I want to keep the code simple to understand for others
2- Unreal has support for multiple platforms and accessing files on other platforms requires third party plugins in some cases.
I recommend glb format  if you plan to use embedded textures here is an example:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Corset/glTF-Binary/Corset.glb

**Comment by zhang8043** [comment]
ok, thank you

**Comment by irajsb** [comment]
I'm going to see if I can add support for external textures using FImageUtils::ImportFileAsTexture2D(FilePath);

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/ExternalTextureImport @zhang8043
